//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CvbAccount
    {
        public int CvbID { get; set; }
        public string CvbUseName { get; set; }
        public string CvbPassword { get; set; }
        public string CvbFullName { get; set; }
        public string CvbEmail { get; set; }
        public string CvbPhone { get; set; }
        public Nullable<bool> CvbAcive { get; set; }
    }
}
