//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvbBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cvbSinhVien
    {
        public string CvbMaSV { get; set; }
        public string CvbHoSV { get; set; }
        public string CvbTenSV { get; set; }
        public Nullable<System.DateTime> CvbNgaySinh { get; set; }
        public Nullable<bool> CvbPhai { get; set; }
        public string CvbPhone { get; set; }
        public string CvbEmail { get; set; }
        public string CvbMaKh { get; set; }
    
        public virtual cvbKhoa cvbKhoa { get; set; }
    }
}
