//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvbBaiKiemTraGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvbK22CNT4Lesson07dbEntities : DbContext
    {
        public CvbK22CNT4Lesson07dbEntities()
            : base("name=CvbK22CNT4Lesson07dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cvbKhoa> cvbKhoa { get; set; }
        public virtual DbSet<cvbSinhVien> cvbSinhVien { get; set; }
    }
}
