//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvbK22CNT4Lesson11_2210900091.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvbLesson11Entities : DbContext
    {
        public CvbLesson11Entities()
            : base("name=CvbLesson11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CvbCategory> CvbCategories { get; set; }
        public virtual DbSet<CvbProduct> CvbProducts { get; set; }
    }
}
