//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvbK22CNT4Lesson11_2210900091.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CvbCategory
    {
        [Display(Name = "Mã danh mục")]
        public int CvbID { get; set; }
        [Display(Name = "Tên danh mục")]
        public string CvbCategory1 { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> CvbStatus { get; set; }
    }
}
