//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvbK22CNT4Lesson11_2210900091.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CvbProduct
    {
        public string CvbId2210900091 { get; set; }
        public string CvbProName { get; set; }
        public Nullable<int> CvbQty { get; set; }
        public Nullable<double> CvbPrice { get; set; }
        public Nullable<int> CvbCateld { get; set; }
        public Nullable<bool> CvbActive { get; set; }
    }
}
